version: '3.8'

services:
  backend:
    image: michaelwieczorek/web-compiler:web-compiler-backend
    deploy:
      replicas: ${BACKEND_REPLICAS}
    depends_on:
      - rabbitmq
      - message-publisher
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - web-net

  frontend:
    image: michaelwieczorek/web-compiler:web-compiler-frontend
    container_name: frontend
    expose:
      - "3000"
    depends_on:
      - message-publisher
    networks:
      - web-net

  message-publisher:
    image: michaelwieczorek/web-compiler:web-compiler-message-publisher
    container_name: message-publisher
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
    networks:
      - web-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Port dla AMQP
      - "15672:15672" # Port dla RabbitMQ Management
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_PASSWORD}
    networks:
      - web-net

  nginx:
    image: michaelwieczorek/web-compiler:web-compiler-nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - web-net

  app-backend:
    image: michaelwieczorek/web-compiler-app-backend
    container_name: web-compiler-app-backend
    depends_on:
      - web-compiler-db
      - vault
    environment:
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - APP_ADMIN_LOGIN=${APP_ADMIN_LOGIN}
      - APP_ADMIN_EMAIL=${APP_ADMIN_EMAIL}
      - APP_ADMIN_PASSWORD=${APP_ADMIN_PASSWORD}
      - VAULT_TOKEN_ID:${VAULT_TOKEN_ID}
    ports:
      - "8084:8084"
    networks:
      - web-net

  vault:
    image: vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN_ID} # Tylko do celów testowych
    ports:
      - "8200:8200" # Port dostępu do Vault
    cap_add:
      - IPC_LOCK # Vault wymaga tej flagi, aby działać bezpiecznie
    command: server -dev -dev-root-token-id="root_token" # Tryb developerski Vault
    networks:
      - web-net

networks:
  web-net:
    driver: bridge
