version: '3.8'

services:
  backend:
    image: web-compiler-backend
    deploy:
      replicas: ${BACKEND_REPLICAS}
    depends_on:
      - rabbitmq
      - message-publisher
    environment:
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - web-net

  frontend:
    image: web-compiler-frontend
    container_name: frontend
    expose:
      - "3000"
    depends_on:
      - message-publisher
    networks:
      - web-net

  message-publisher:
    image: web-compiler-message-publisher
    container_name: message-publisher
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
    networks:
      - web-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # port dla AMQP
      - "15672:15672" # port dla RabbitMQ Management
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_PASSWORD}
    networks:
      - web-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web-net

  web-compiler-db:
    image: web-compiler-db
    container_name: web-compiler-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - web-compiler-db

  web-compiler-app-backend:
    image: web-compiler-app-backend
    container_name: web-compiler-app-backend
    depends_on:
      - rabbitmq
      - web-compiler-db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=web-compiler-db
      - DB_PORT=5432
    ports:
      - "8084:8084"
    networks:
      - web-net

networks:
  web-net:
    driver: bridge
